### ISSUE TITLE
enable optional properties in the schema 

### ISSUE THREAD

**Issue by Ali-khadembashi** [Ali-khadembashi/M90-express-back-end#1]
in addition to existing keys for each end points, want  to be able to add additional keys that are optional to fill

**Comment by MohammadProAcc** [comment]
steps to add a property to a model

1. add property to model's schema
2. update the corresponding router which consist of :
  2.1. add property to route's validation ( if you want the property to be optional, don't call `required()` method in validation )
  2.2. add corresponding logic to route's controller
